# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-20.04

steps:

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'Test_AWS_Terraform'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: 'terraform init'
    displayName: 'iniciar terraform'
    
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'Test_AWS_Terraform'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: 'terraform plan -var-file=configuration/backend.tfvars'
    displayName: 'plan de tteraform'
    
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'Test_AWS_Terraform'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: 'terraform apply -var-file=configuration/backend.tfvars auto-approve'
    displayName: 'terraform apply'
    
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'Test_AWS_Terraform'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: 'terraform destroy -var-file=configuration/backend.tfvars auto-approve'
    displayName: 'finalizar con terraform'
