# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-20.04

steps:
- script: echo Hello, world SWO123fin!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: echo test terraform!
  displayName: 'Test terraformSWO'

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'Test_AWS_Terraform'
    regionName: 'us-east-1'
    scriptType: 'inline'
    inlineScript: |
      # You can write your script inline here
      aws sts get-caller-identity